package com.dtb.jdbc.model;
// Generated Apr 6, 2019 9:59:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private long id;
	private String cpf;
	private String nome;
	private String email;

	public Cliente() {
	}

	public Cliente(long id, String cpf, String nome) {
		this.id = id;
		this.cpf = cpf;
		this.nome = nome;
	}

	public Cliente(long id, String cpf, String nome, String email) {
		this.id = id;
		this.cpf = cpf;
		this.nome = nome;
		this.email = email;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "Cliente [id=" + id + ", cpf=" + cpf + ", nome=" + nome + ", email=" + email + "]";
	}
	
	

}
