package com.dtb.jdbc.model;
// Generated Apr 6, 2019 9:59:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	private long id;
	private String nome;
	private Integer valor;
	private String url;

	public Curso() {
	}

	public Curso(long id) {
		this.id = id;
	}

	public Curso(long id, String nome, Integer valor, String url) {
		this.id = id;
		this.nome = nome;
		this.valor = valor;
		this.url = url;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Override
	public String toString() {
		return "Curso [id=" + id + ", nome=" + nome + ", valor=" + valor + ", url=" + url + "]";
	}
	
	

}
