package com.dtb.jdbc.model;
// Generated Apr 6, 2019 9:59:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento implements java.io.Serializable {

	private long id;
	private String cpf;
	private long idCurso;
	private String dataInscricao;

	public Pagamento() {
	}

	public Pagamento(long id, String cpf, long idCurso, String dataInscricao) {
		this.id = id;
		this.cpf = cpf;
		this.idCurso = idCurso;
		this.dataInscricao = dataInscricao;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public long getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(long idCurso) {
		this.idCurso = idCurso;
	}

	public String getDataInscricao() {
		return this.dataInscricao;
	}

	public void setDataInscricao(String dataInscricao) {
		this.dataInscricao = dataInscricao;
	}

	@Override
	public String toString() {
		return "Pagamento [id=" + id + ", cpf=" + cpf + ", idCurso=" + idCurso + ", dataInscricao=" + dataInscricao
				+ "]";
	}
	
	

}
